### ISSUE TITLE
Link in Pull Request template broken

### ISSUE THREAD

**Issue by mmaelicke** [Open-Environmental-Science/awesome-open-hydrology#10]
Hey,
The link on the last bullet point in the [Pull Request Template](https://github.com/Open-Environmental-Science/awesome-open-hydrology/blob/master/.github/PULL_REQUEST_TEMPLATE.md) is broken.

I am note sure where it should point to as `http://titlecapitalization.com/`, as well as `https://titlecapitalization.com/` are not working.

What I found is: 

* https://capitalizemytitle.com/
* https://titlecaseconverter.com/
* https://headlinecapitalization.com/

In any case I am not sure what the link was intending. Refering a *converter* or *information* on title capitalization?

**Comment by schymans** [comment]
Good call! I think we could directly link to: https://capitalizemytitle.com/#APStyle
