### ISSUE TITLE
Statement on Code 'status'

### ISSUE THREAD

**Issue by mmaelicke** [Open-Environmental-Science/awesome-open-hydrology#6]
Hey there,

Thanks for this awesome list!
I think you/we would need an additional statement on code status (how complete? alpha- beta etc). JOSS doesn't want any, what they call 'half-baked' code.  Well, from my point of view, for a journal that's perfectly fine, but what about this list?
I, myself,  have been and I am involved in some in-development projects. They are 'half-baked' in the sense that there is WAY more to do to release a `v1.0`, but they are functional. Sometimes people are working on the same things and after years they realize: an earlier coop would have been awesome!
One example is the [Geostat-Framework's gstools](https://github.com/GeoStat-Framework/GSTools)  (which definitely should go on this list, PR will follow) and my own [scikit-gstat](https://github.com/mmaelicke/scikit-gstat) (which is far from v1.0, but already used in thesis, summer schools and lectures by other people than myself).

From my point of view, this is also part of our story and open source, that we have a lot of ongoing developments, where collaboration could be really helpful, if you just knew about the other projects.

Maybe you comment on this, what do you think? If you agree, I can also push a PR over suggesting some text, or something like that.
Keep up and all the best,

Mirko

**Comment by schymans** [comment]
Great idea! Admittedly, I have not thought about this; I though if it is useful, it should be here, so I added my own ESSM, although it is v0.4x. But to give such a label, we would need some guidance on how to assess. Do you want to propose something in the awesome.md manifesto?
